#!/bin/sh

# This script requires xdotool for the clickable workspace switcher

source $(dirname $0)/config

# Loop output to the panel
while :
do

clock=`date +"%a %d %b %H:%M"`

# Save our output into a variable to pipe it to the panel
for ((i=0;i<=$workspaces;i++))
do
	cws=`xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'`
	
	if [ $cws -eq $i ]; then
		ws=$ws$cbg$cfg$circle
	else	
		#ws=$ws$cbg$cfg$circle2
		ws="$ws^ca(1, xdotool key Super+$(($i + 1)))$cbg$cfg$circle2^ca()"
	fi
done

# Send the output
echo "$ws$tbg$tfg$lwst"

# Reset variables and arrays
ws=""

# Sleep for 0.3s before we start over
sleep 0.3

done
