#!/bin/sh

# Prints a volume icon and the volume level to dzen2

source $(dirname $0)/config

while :
do 
	vol=$(amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq)
	mute="$(amixer get Master | sed -n 's/^.*\[\([f-o]\+\).*$/\1/p')"
	
	# Checks volume levels and mute stauts to determine which icon to display
    if [ "$mute" = "off" ] || [[ $vol -eq 0 ]]; then
		volicon=$vm
		vol="$vol%   "
	else
		if [[ $vol -ge 100 ]]; then
			volicon=$vf
			vol="$vol% "
		elif [[ $vol -le 99 ]] && [[ $vol -ge 10 ]]; then
			volicon=$vh
			vol="$vol%  "
		elif [[ $vol -ge 1 ]] && [[ $vol -le 9 ]]; then
			volicon=$vh
			vol="$vol%   "
		fi
	fi
	
	echo "$tbg$tfg$lt$fg$bg$volicon $vol"
        sleep 1 
done
