#!/bin/sh

while true
do
    batt_info=`acpi -b | sed 's/,//g'`
    batt_level=$(echo $batt_info | sed 's/%//' | awk '{ print $4 }' )

    if [[ $batt_level -le 10 ]]; then
        icon=
        notify-send -u critical -a "Battery Monitor" "Battery CRITICAL" "Battery capacity at less than 10%, plug in NAO!"
    elif [[ $batt_level -le 50 ]]; then
        icon=
    elif [[ $batt_level -ge 80 ]]; then
        icon=
    else
        icon=
    fi
    echo $batt_info \
        | sed 's/Battery 0: /panel_battery/' \
        | sed -r 's/Charging|Unknown/%{F#a6e22e}%{F-}/' \
        | sed "s/Discharging/%{F#a6e22e}$icon%{F-}/" \
        | sed 's/ until charg.*$//' \
        | sed 's/ charging at.*$//' \
        | sed 's/ remain.*$//' \
        | sed -r 's/([0-9]{2}:[0-9]{2}:[0-9]{2})$/\(\1\)/g'
    sleep 10
done
