#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        panel_battery*)
            # battery info
            battery_info="${line#panel_battery}"
            ;;
        panel_memory*)
            # memory info
            memory_info="${line#panel_memory}"
            ;;
        panel_clock*)
            # clock output
            date_info="${line#panel_clock}"
            ;;
        panel_load*)
            # load avg
            load_info="${line#panel_load}"
            ;;
        panel_cpu*)
            # cpu usage
            cpu_info="${line#panel_cpu}"
            ;;
        panel_volume*)
            # volume
            vol_info="${line#panel_volume}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos %{U#a6e22e}%{+u}${name}%{-u}%{U-}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos %{U#66d9ef}%{F#909090}%{+u}${name}%{-u}%{F-}%{U-}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos %{U#909090}%{+u}${name}%{-u}%{U-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos ${name}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos %{F#909090}${name}%{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos %{B#f92672}${name}%{B-}"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos    %{F#5e7175}$layout%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{S+} $wm_infos%{c}$date_info%{r}$cpu_info $memory_info $vol_info $battery_info "
done
