directory: /media/music
library: /media/music/library.blb
import:
    move: yes
    write: yes
plugins: convert fromfilename lyrics mbsync scrub fetchart embedart mpdstats mpdupdate
embedart:
    auto: no
mpd:
    host: localhost
    port: 6600
