#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i

bspc config top_padding        14

# Visual
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

bspc rule -a Skype   pseudo_tiled=on
bspc rule -a Gimp    desktop=^8 follow=on floating=on
bspc rule -a Firefox desktop=^2
bspc rule -a mplayer floating=on

# Launch bar
$HOME/.config/bspwm/panel/panel &
