# zsh configuration file
# Start X, if not already started on first tty.
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

# Set ZSHC to the current directory.
ZSHC="$(dirname "${BASH_SOURCE:-$0}")"
ZSH_CUSTOM="$ZSHC/custom"
# Disable auto-update notifications (updating is handled via pacman).
DISABLE_AUTO_UPDATE=true

plugins=(archlinux cdenv git ssh-agent tmux tmuxinator vagrant)
setopt completealiases
setopt histignoredups
# Make `cd` function like `pushd`.
setopt autopushd
unsetopt correct_all
# Command execution time stamp shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# TMUX configuration.
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOCONNECT=false

# Enable oh-my-zsh and zsh theme.
ZSH="$ZSHC/oh-my-zsh"
ZSH_THEME="nanotech"
source "$ZSH/oh-my-zsh.sh"

# Disable autocorrect.
DISABLE_CORRECTION="true"
unsetopt correct
unsetopt correct_all

# Base16 shell
BASE16_SCHEME="tomorrow.dark"
BASE16_SHELL="$ZSHC/base16-shell/base16-$BASE16_SCHEME.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

# rupa/z
if [ -f "$ZSH_CUSTOM/z.sh" ]; then
    . $ZSH_CUSTOM/z.sh
fi

if [ -f /usr/share/doc/pkgfile/command-not-found.zsh ]; then
    source /usr/share/doc/pkgfile/command-not-found.zsh
fi

if [ -f "$ZSHC/zsh_sudo" ]; then
    while read -r COMMAND; do
        alias $COMMAND="sudo $COMMAND"
    done < "$ZSHC/zsh_sudo"
fi

if [ -f "$ZSHC/zsh_aliases" ]; then
    source "$ZSHC/zsh_aliases"
fi

export EDITOR=nano
export PATH="/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/core_perl:/opt/java/bin:$HOME/.cabal/bin:$HOME/.bin:/usr/games"
export LD_LIBRARY_PATH="/usr/local/lib"
export PAGER=less
export SSH_KEY_PATH="~/.ssh/id_rsa"
export R_LIBS="~/.r/libs"

export LANG=en_CA.UTF-8
export LC_CTYPE=en_CA.UTF-8
export LC_NUMERIC="en_CA.UTF-8"
export LC_TIME="en_CA.UTF-8"
export LC_COLLATE="en_CA.UTF-8"
export LC_MONETARY="en_CA.UTF-8"
export LC_MESSAGES=C
export LC_PAPER="en_CA.UTF-8"
export LC_NAME="en_CA.UTF-8"
export LC_ADDRESS="en_CA.UTF-8"
export LC_TELEPHONE="en_CA.UTF-8"
export LC_MEASUREMENT="en_CA.UTF-8"
export LC_IDENTIFICATION="en_CA.UTF-8"
