#!/bin/sh

# Set keyboard layout
#setxkbmap -layout se

# dzen2 settings
screenwidth=`xrandr --current | grep current | awk '{print $8}'`
panel1width=`printf "%.0f" $(echo "scale=5; (45.572916*$screenwidth)/100" | bc)`
panel2width=`printf "%.0f" $(echo "scale=5; (10.41600*$screenwidth)/100" | bc)`
panel3width=`printf "%.0f" $(echo "scale=5; (40.10416*$screenwidth)/100" | bc)`
panel4width=`printf "%.0f" $(echo "scale=5; (3.90625*$screenwidth)/100" | bc)`
panel2slavewidth=`printf "%.0f" $(echo "scale=5; (8.33333*$screenwidth)/100" | bc)`
panel2xoffset=$panel1width
panel3xoffset=$(($panel2xoffset + $panel2width))
panel4xoffset=$(($panel3xoffset + $panel3width))
panelheight=18
font="-*-tamsynmod-medium-r-normal-*-14-101-100-100-c-70-iso8859-1"

# Start the 3 dzen panels to create the statusbar
$HOME/.config/2bwm/panel/panel | dzen2 -p -ta l -fn "$font" -h $panelheight -tw $panel1width &
$HOME/.config/2bwm/panel/calendar | dzen2 -p -u -fn "$font" -x $panel2xoffset -tw $panel2width -h $panelheight -w $panel2slavewidth -sa c -l 8 -e 'button1=togglecollapse' &
conky -c $HOME/.config/2bwm/panel/panel_conky | dzen2 -p -ta r -fn "$font" -x $panel3xoffset -h $panelheight -tw $panel3width &
$HOME/.config/2bwm/panel/volume | dzen2 -p -fn "$font" -x $panel4xoffset -h $panelheight -tw $panel4width -e 'button5=exec:amixer set Master 5%-:;button4=exec:amixer set Master 5%+:;button1=exec:amixer set Master toggle:' &

exec ~/.2bwm/2bwm
